name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=00ff41&color_dots=#0d1117,#003300,#006600,#00cc00,#00ff41
            dist/github-contribution-grid-snake-dark.svg?color_snake=00fff9&color_dots=#0d1117,#0a2a2a,#0a4a4a,#00cccc,#00fff9
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
